---
version: "3.7"

networks:
  default:
    name: kind
    external: true

services:
  minio:
    container_name: minio
    image: quay.io/minio/minio:RELEASE.2023-03-22T06-36-24Z
    labels:
      - VIRTUAL_PORT=9090
    command: server /data --console-address ":9090"
    environment:
      - MINIO_ROOT_USER=ROOTNAME
      - MINIO_ROOT_PASSWORD=CHANGEME123

  websrv:
    container_name: websrv
    image: ghcr.io/samerbahri98/terraform-helm-launcher-nginx-test:main
    labels:
      - VIRTUAL_PORT=80
