---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: molecule
    image: gitea.thebahrimedia.com/vps/ansible-local-ee:latest
    pre_build_image: true
    privileged: true
    command: tail -f /dev/null
    cgroupns_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - .:/chart:ro
    env:
      KUBECONFIG: /root/.kube/config
      K8S_AUTH_KUBECONFIG: /root/.kube/config
      KUBE_CONFIG_PATH: /root/.kube/config
    networks:
      - name: kind
provisioner:
  name: ansible
  inventory:
    links:
      hosts: ./inventory/hosts
      host_vars: ./inventory/host_vars
  env:
    LOCAL_TFM_PATH: /tfm
    LOCAL_BIN_PATH: /_bin
    KUBECONFIG: /root/.kube/config
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    cleanup: cleanup.yml
verifier:
  name: ansible
