---
- hosts: molecule
  name: prepare_remote
  tasks:
    - name: Create Kind Cluster
      ansible.builtin.command: |-
        {{
          LOCAL_BIN_PATH
        }}/kind create cluster --config={{
          LOCAL_TFM_PATH
        }}/k8s_minio/molecule/default/files/Cluster.yaml
      changed_when: false
      ignore_errors: true
      failed_when: false

    - name: Refresh Inventory
      ansible.builtin.meta: refresh_inventory

    - name: Fix Kubeconfig API Address
      ansible.builtin.replace:
        path: ~/.kube/config
        regexp: 127.0.0.1
        replace: |-
          {{
            hostvars['molecule-control-plane']['docker_networksettings']
            ['Networks']['kind']['IPAddress']
          }}

    - name: Copy Kubeconfig File
      ansible.builtin.fetch:
        src: /root/.kube/config
        dest: /tmp/.k8sconfig
        validate_checksum: true
