---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tflauncher.fullname" . }}
  labels:
    {{- include "tflauncher.labels" . | nindent 4 }}
data:
  {{- if .Values.netrc.create }}
  .netrc: {{ include "tflauncher.netrc" . | b64enc }}
  {{- end }}
  .tfvars: {{ tpl .Values.tfvarsFile . | default "" | b64enc | quote }}
  backend.tf: {{ tpl .Values.backend.file . | default "" | b64enc | quote }}
