---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tflauncher.fullname" . }}
  labels:
    {{- include "tflauncher.labels" . | nindent 4 }}
data:
  init.sh: |
    #! /bin/sh

    terraform -chdir=/workspace init \
      -var-file=/credentials/.tfvars \ 
      -upgrade \
      -migrate-state \
      -backend-config=/credentials/backend.tf \
      -from-module={{ .Values.rootModule }} \
      -force-copy \
      -input=false \
      -no-color;
    
    terraform -chdir=/workspace refresh \
      -var-file=/credentials/.tfvars \
      -input=false \
      -no-color;

    terraform -chdir=/workspace apply \
      -var-file=/credentials/.tfvars \
      -auto-approve \
      -input=false \
      -no-color;
    
    terraform -chdir=/workspace output -no-color -json > /output/{{ include "tflauncher.fullname" . }}-output.json;
  save.sh: |
    #! /bin/sh

    OUTPUT_BASE64=$(base64 -w 0 /output/{{ include "tflauncher.fullname" . }}-output.json)

    sed "s/\$\$/$OUTPUT_BASE64/" output.yaml > /tmp/output.yaml

    kubectl apply -f /tmp/output.yaml
  output.yaml: |
    apiVersion: v1
    kind: Secret
      metadata:
        name: {{ include "tflauncher.fullname" . }}-output
        labels:
          {{- include "tflauncher.labels" . | nindent 10 }}
      data:
        output.json: "$$"
