---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tflauncher.fullname" . }}
  labels:
    {{- include "tflauncher.labels" . | nindent 4 }}
data:
  init.sh: |
    #! /bin/sh

    echo "====== TF INIT ======";
    terraform -chdir=/workspace init \
      -from-module={{ .Values.module.source }} \
      -get=true \
      -force-copy \
      -input=false \
      -no-color;

    echo "====== TF INIT ======";
    terraform -chdir=/workspace/modules/{{ .Values.module.name }} init \
      -upgrade \
      -migrate-state \
      -var-file=/credentials/.tfvars \
      -backend-config=/credentials/backend.tf \
      -get=true \
      -force-copy \
      -input=false \
      -no-color;

    echo "====== TF IMPORT ======";
    terraform -chdir=/workspace/modules/{{ .Values.module.name }} import \
      -config=/workspace/modules/{{ .Values.module.name }} \
      -input=false \
      -var-file=/credentials/.tfvars \
      -no-color;
    
    echo "====== TF REFRESH ======";
    terraform -chdir=/workspace/modules/{{ .Values.module.name }} refresh \
      -var-file=/credentials/.tfvars \
      -input=false \
      -no-color;

    echo "====== TF APPLY ======";
    terraform -chdir=/workspace/modules/{{ .Values.module.name }} apply \
      -var-file=/credentials/.tfvars \
      -auto-approve \
      -input=false \
      -no-color;

    echo "====== TF OUTPUT ======";
    terraform -chdir=/workspace/modules/{{ .Values.module.name }} output -json > /tmp/{{ include "tflauncher.fullname" . }}-output.json;
  save.sh: |
    #! /bin/sh

    OUTPUT_BASE64=$(base64 -w 0 /tmp/{{ include "tflauncher.fullname" . }}-output.json)

    sed 's/\$\$/'"$OUTPUT_BASE64"'/g' /entrypoint.d/output.yaml > /tmp/output.yaml

    cat /tmp/output.yaml

    kubectl apply -f /tmp/output.yaml
  output.yaml: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: {{ include "tflauncher.fullname" . }}-output
      labels:
        {{- include "tflauncher.labels" . | nindent 10 }}
    data:
      output.json: "$$"
  # main.tf: |
  #   terraform {
  #     backend "{{ .Values.backend.type }}" {}
  #     required_version = "{{ .Values.requiredVersion }}"
  #   }
