{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tflauncher.serviceAccountName" . }}
  labels:
    {{- include "tflauncher.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "tflauncher.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["v1"]
    resources: ["secrets"]
    verbs: ["create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tflauncher.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "tflauncher.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "tflauncher.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
