---
name: Release Helm Chart

'on':
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - 'http_public'
          - 'http_private'
    services:
      websrv:
        image: 

    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-helm@v3
      - uses: helm/kind-action@v1.4.0

      - name: Deploy Minio
        run: |
          docker run -dt \
            --name "minio" \
            -e "MINIO_ROOT_USER=ROOTNAME" \
            -e "MINIO_ROOT_PASSWORD=CHANGEME123" \
            --network "kind" \
            quay.io/minio/minio:RELEASE.2023-03-22T06-36-24Z \
            server /data

      - name: Deploy Web Server
        run: |
          docker run -dt \
            --name "websrv" \
            --network "kind" \
            ghcr.io/samerbahri98/terraform-helm-launcher-nginx-test:main

      - name: Install Chart
        run: |
          helm install tflauncher-${{ matrix.test }} . \
            -n tflauncher --create-namespace \
            -f ./test-values/${{ matrix.test }}.yml
